[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = [
  "npm install",
  "npx --yes prisma generate"
]

[phases.build]
cmds = ["npm run build:api"]

[start]
cmd = "node_modules/.bin/prisma migrate deploy && node apps/api/dist/main"
